#!/usr/bin/php
<?php
require('init.php');
$router = new \resource\Router();

$task = ucfirst($router->getTask());
$action = $router->getAction();
$class = 'worker\\'.$task;
$class = new $class();

try{
    if(method_exists($class, $action)){
        if(isset($router->body['loop'])){
            $loop = 0;
            while ($loop < intval($router->body['loop'])){
                $class->$action();
                $loop ++;
            }
        }else{
            $class->$action();
        }
    }else{
        exit('action is not found in \''.$task.'\'.');
    }
}catch (Exception $e){
    echo $e->getMessage().EOL;
}